import {
  Controller,
  Get,
  Post,
  Body,
  BadRequestException,
  HttpCode,
  HttpStatus,
  Logger,
} from "@nestjs/common";
import { OrgId } from "../common/org-context.decorator";
import { PrismaService } from "../prisma/prisma.service";
import { IcpAutoService } from "./icp-auto.service";
import { GraphService } from "../graph/graph.service";

type PipelineRunDto = {
  id: string;
  type: "full" | "source" | "enrich" | "score" | "crm" | "sequence";
  status: "running" | "success" | "failed" | "queued";
  processed: number;
  durationMs: number;
  startedAt: string;
};

const STAGE_TO_TYPE: Record<string, PipelineRunDto["type"]> = {
  COMPANY_DISCOVERY: "source",
  PEOPLE_DISCOVERY: "source",
  IDENTITY_RESOLUTION: "enrich",
  CONTACT_ENRICHMENT: "enrich",
  SCORING: "score",
};

const STATUS_MAP: Record<string, PipelineRunDto["status"]> = {
  QUEUED: "queued",
  RUNNING: "running",
  COMPLETED: "success",
  FAILED: "failed",
};

@Controller("pipeline")
export class PipelineController {
  private readonly logger = new Logger(PipelineController.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly icpAuto: IcpAutoService,
    private readonly graph: GraphService,
  ) {}

  /**
   * Canonical trigger: run the newest (current) ICP in the org.
   * If the org has no ICPs at all, auto-generate one from their website
   * (scrape + LLM extraction) and run discovery on that.
   *
   * Best-effort — if any one ICP fails to enqueue (e.g. already running),
   * we skip it and continue with the rest.
   */
  @Post("run")
  @HttpCode(HttpStatus.ACCEPTED)
  async run(
    @OrgId() orgId: string | undefined,
    @Body() body: { stage?: unknown } | undefined,
  ) {
    if (!orgId) throw new BadRequestException("orgId required");
    if (body?.stage !== undefined && body.stage !== "full") {
      throw new BadRequestException(
        'Only the full guarded pipeline is available; stage must be exactly "full" or omitted',
      );
    }

    const currentProfile = await this.prisma.icpProfile.findFirst({
      where: { orgId },
      select: { id: true, name: true },
      orderBy: { updatedAt: "desc" },
    });
    let profiles = currentProfile ? [currentProfile] : [];

    let autoGenerated: { id: string; name: string } | null = null;
    if (profiles.length === 0) {
      autoGenerated = await this.icpAuto.generateForOrg(orgId);
      profiles = [autoGenerated];
    }

    // Hand off to the LangGraph supervisor — it orchestrates sourcing →
    // enrichment → scoring → human approval → outreach with checkpointed
    // state per stage. Returns immediately; the graph runs in the background.
    let graphRun: { runId: string; threadId: string } | null = null;
    let skipReason: string | null = null;
    try {
      graphRun = await this.graph.runPipelineGraph(
        orgId,
        profiles.map((p) => p.id),
      );
    } catch (err) {
      skipReason = err instanceof Error ? err.message : "unknown";
      this.logger.warn(`Graph run not started: ${skipReason}`);
    }

    return {
      message: autoGenerated
        ? `Auto-generated ICP "${autoGenerated.name}" and started pipeline graph`
        : graphRun
          ? "Pipeline graph started for the current ICP profile"
          : `Pipeline could not start: ${skipReason}`,
      autoGenerated,
      graphRunId: graphRun?.runId ?? null,
      triggered: graphRun ? profiles.map((p) => ({ icpProfileId: p.id, name: p.name })) : [],
      skipped: graphRun
        ? []
        : profiles.map((p) => ({ icpProfileId: p.id, name: p.name, reason: skipReason ?? "unknown" })),
      stage: "full" as const,
    };
  }

  /**
   * Recent pipeline runs in the org, mapped to the frontend's PipelineRun
   * shape. Returns the 20 most recent ScrapeJob rows.
   */
  @Get("status")
  async status(
    @OrgId() orgId: string | undefined,
  ): Promise<{ runs: PipelineRunDto[] }> {
    if (!orgId) throw new BadRequestException("orgId required");

    const jobs = await this.prisma.scrapeJob.findMany({
      where: { orgId },
      orderBy: { createdAt: "desc" },
      take: 20,
      select: {
        id: true,
        stage: true,
        status: true,
        processedItems: true,
        startedAt: true,
        completedAt: true,
        createdAt: true,
      },
    });

    const runs: PipelineRunDto[] = jobs.map((j) => {
      const started = j.startedAt ?? j.createdAt;
      const ended = j.completedAt ?? new Date();
      const durationMs = j.startedAt ? ended.getTime() - started.getTime() : 0;
      return {
        id: j.id,
        type: STAGE_TO_TYPE[j.stage] ?? "source",
        status: STATUS_MAP[j.status] ?? "queued",
        processed: j.processedItems,
        durationMs,
        startedAt: started.toISOString(),
      };
    });

    return { runs };
  }
}
