import { ReplyIntent10 } from "@prisma/client";

export interface EvidenceSpan {
  readonly start: number;
  readonly end: number;
  readonly text: string;
}

export interface DeterministicClassification {
  readonly intent: ReplyIntent10;
  readonly confidence: number;
  readonly rawOutput: unknown;
  readonly evidenceSpans?: readonly EvidenceSpan[];
}

export interface DeterministicInput {
  readonly fromEmail?: string | null;
  readonly subject?: string | null;
  readonly bodyText?: string | null;
  readonly headers?: Readonly<Record<string, string | undefined>> | null;
}

function normalizeHeaderKey(key: string): string {
  return key.trim().toLowerCase();
}

function headerValue(
  headers: Readonly<Record<string, string | undefined>> | null | undefined,
  name: string,
): string {
  if (!headers) return "";
  const v = headers[normalizeHeaderKey(name)];
  return typeof v === "string" ? v : "";
}

function findFirstSpan(text: string, regex: RegExp): EvidenceSpan | null {
  const match = regex.exec(text);
  if (!match || typeof match.index !== "number") return null;
  const start = match.index;
  const end = start + match[0].length;
  return { start, end, text: text.slice(start, end) };
}

const RE_OOO = /\b(out of office|currently away)\b/i;
const RE_UNSUB = /\b(unsubscribe|remove me|stop emailing)\b/i;
const RE_LEGAL = /\b(cease and desist|legal action|spam complaint)\b/i;

export function classifyDeterministic(
  input: DeterministicInput,
): DeterministicClassification | null {
  const body = (input.bodyText ?? "").trim();
  const fromEmail = (input.fromEmail ?? "").toLowerCase();

  const autoSubmitted = headerValue(input.headers, "Auto-Submitted").toLowerCase();
  const xAutoreply = headerValue(input.headers, "X-Autoreply").toLowerCase();
  const contentType = headerValue(input.headers, "Content-Type").toLowerCase();

  // 1) bounce_or_ndr — strong MIME/header/from signals.
  const isMultipartReport = contentType.startsWith("multipart/report");
  const isAutoGenerated = autoSubmitted.startsWith("auto-generated");
  const isDaemon =
    fromEmail.includes("mailer-daemon") || fromEmail.includes("postmaster");
  if (isMultipartReport || isAutoGenerated || isDaemon) {
    return {
      intent: ReplyIntent10.bounce_or_ndr,
      confidence: 1.0,
      rawOutput: {
        stage: "stage1",
        rule: "bounce_or_ndr",
        signals: {
          contentType: contentType || null,
          autoSubmitted: autoSubmitted || null,
          fromEmail: input.fromEmail ?? null,
        },
      },
      evidenceSpans: body
        ? (() => {
            const span = findFirstSpan(body, /\b(mailer-daemon|postmaster)\b/i);
            return span ? [span] : undefined;
          })()
        : undefined,
    };
  }

  // 2) auto_reply_ooo — Auto-Submitted/X-Autoreply headers or body phrase.
  const isAutoReplied = autoSubmitted.startsWith("auto-replied");
  const isXAutoreplyYes = xAutoreply === "yes";
  const oooSpan = body ? findFirstSpan(body, RE_OOO) : null;
  if (isAutoReplied || isXAutoreplyYes || oooSpan) {
    return {
      intent: ReplyIntent10.auto_reply_ooo,
      confidence: 1.0,
      rawOutput: {
        stage: "stage1",
        rule: "auto_reply_ooo",
        signals: {
          autoSubmitted: autoSubmitted || null,
          xAutoreply: xAutoreply || null,
        },
      },
      evidenceSpans: oooSpan ? [oooSpan] : undefined,
    };
  }

  // 3) spam_or_legal_threat — legal/spam complaint phrases.
  const legalSpan = body ? findFirstSpan(body, RE_LEGAL) : null;
  if (legalSpan) {
    return {
      intent: ReplyIntent10.spam_or_legal_threat,
      confidence: 1.0,
      rawOutput: { stage: "stage1", rule: "spam_or_legal_threat" },
      evidenceSpans: [legalSpan],
    };
  }

  // 4) unsubscribe — explicit request + short body.
  const unsubSpan = body ? findFirstSpan(body, RE_UNSUB) : null;
  if (unsubSpan && body.length < 200) {
    return {
      intent: ReplyIntent10.unsubscribe,
      confidence: 1.0,
      rawOutput: { stage: "stage1", rule: "unsubscribe", bodyLength: body.length },
      evidenceSpans: [unsubSpan],
    };
  }

  return null;
}

